pipeline {
    agent {
        docker { image 'otus-qa' }
    }
    environment {
        JAVA_HOME = "${tool 'jdk'}"
        PATH    = "${env.JAVA_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Test') {
            steps {
                sh 'python --version'
                sh 'pytest --url=http://demo23.opencart.pro/admin --browser_type=chrome --window_option=headless lesson_27/test_lesson_27.py'
                sh 'pytest lesson_18/test_lesson_18.py --url=http://demo23.opencart.pro/admin --browser_type=chrome --capture=no --verbose --alluredir=report'
                dir("allure-2.10.0/bin") {
                    sh 'allure generate --clean ../../report -o ../../report_build'
                }
                sh 'ls'
            }
        }
    }
    post{
        always {
            allure([
                includeProperties: true,
                jdk              : '',
                properties       : [],
                reportBuildPolicy: 'ALWAYS',
                results          : [[path: 'report_build']]
            ])
        }
    }
}