pipeline {
    agent {
        docker { image 'otus-qa' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'python --version'
                sh 'pytest lesson_18/test_lesson_18.py --url=http://demo23.opencart.pro/admin --browser_type=chrome --capture=no --verbose --alluredir=report'
                sh 'cd allure-2.10.0/bin'
                sh 'allure generate ../../report -o ../../report_build'

            }
        }
    }
    post{
        always {
            allure([
                includeProperties: true,
                jdk              : '',
                properties       : [],
                reportBuildPolicy: 'ALWAYS',
                results          : [[path: 'report_build']]
            ])
        }
    }
}